### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by bamal** [jmdana/memprof#20]
I have installed the memoryprof library but I have this error 

```
Traceback (most recent call last):
  File "/home_sq/aboukhdhir/miniconda3/lib/python3.6/site-packages/memprof/mp_utils.py", line 67, in gen_plot
    item, size = line.split('\t')
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./kmeans_parcellation.py", line 84, in <module>
    main(sys.argv[1:])
  File "./kmeans_parcellation.py", line 76, in main
    seed = seed, verbose = verbose)
  File "/home_sq/aboukhdhir/miniconda3/lib/python3.6/site-packages/memprof/memprof.py", line 157, in __call__
    gen_plot(self.__logfile, self.threshold)
  File "/home_sq/aboukhdhir/miniconda3/lib/python3.6/site-packages/memprof/mp_utils.py", line 83, in gen_plot
    times.append(float(line))
ValueError: could not convert string to float: ```

**Comment by jmdana** [comment]
Do you have any data in the generated logfiles? If they are empty you might need to tune the minimum variable size:

https://github.com/jmdana/memprof#adjusting-the-threshold

**Comment by bamal** [comment]
Yes I have data in the logfiles and it works fine for some functions and returns that error in some cases .. I will try to tune the minimum variable size

**Comment by jmdana** [comment]
My guess is that the exception occurs because one of the functions doesn't have a single variable within the threshold. Could you please upload your logfiles somewhere so I can debug the issue and fix it?
