### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by Arti3DPlayer** [jmdana/memprof#9]
failed to import Cython: /usr/local/lib/python2.7/dist-packages/Cython/Compiler/Scanning.so: undefined symbol: PyUnicodeUCS2_Contains

error: Cython does not appear to be installed

---

Command /usr/bin/python -c "import setuptools;**file**='/tmp/pip-build-root/memprof/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-_x4MCW-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip-build-root/memprof

Cython reinstall not helped.

**Comment by imirzov** [comment]
Hi, I have the same problem:

```
C:\Users\ihor>python -m pip install cython
Collecting cython
  Downloading Cython-3.0.7-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
Downloading Cython-3.0.7-cp311-cp311-win_amd64.whl (2.8 MB)
  ---------------------------------------- 2.8/2.8 MB 2.0 MB/s eta 0:00:00
Installing collected packages: cython
  WARNING: The scripts cygdb.exe, cython.exe and cythonize.exe are installed in 'C:\Users\ihor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cython-3.0.7

C:\Users\ihor>python -m pip install memprof
Collecting memprof
  Using cached memprof-0.3.6.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "<string>", line 23, in <module>
      ModuleNotFoundError: No module named 'Cython'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\ihor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\ihor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ihor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ihor\AppData\Local\Temp\pip-build-env-o7h_1bpq\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ihor\AppData\Local\Temp\pip-build-env-o7h_1bpq\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\ihor\AppData\Local\Temp\pip-build-env-o7h_1bpq\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\ihor\AppData\Local\Temp\pip-build-env-o7h_1bpq\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 28, in <module>
      AttributeError: module 'setuptools.command.easy_install' has no attribute 'main'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```
